# Generated by Django 4.1.5 on 2023-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0006_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
