# Generated by Django 4.1.5 on 2023-02-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0007_member_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(null=True)),
                ('total_years_of_exp', models.IntegerField(null=True)),
                ('current_comp', models.CharField(max_length=255, null=True)),
                ('years_last_comp', models.IntegerField(null=True)),
                ('amount_of_workplaces', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='desired_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.IntegerField(null=True),
        ),
    ]
