# Generated by Django 4.1.5 on 2023-02-15 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0008_work_remove_member_is_favorite_member_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_id',
            new_name='amount_of_workplaces',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='current_comp',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='amount_of_workplaces',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='total_years_of_exp',
            new_name='years',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_id',
        ),
        migrations.RemoveField(
            model_name='work',
            name='years_last_comp',
        ),
        migrations.AddField(
            model_name='member',
            name='total_years_of_exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='mId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='crm_project.member'),
        ),
        migrations.AddField(
            model_name='work',
            name='sphere',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
