# Generated by Django 4.1.7 on 2023-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0010_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='years',
            field=models.FloatField(null=True),
        ),
    ]
