# Generated by Django 4.1.7 on 2023-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0012_remove_work_sphere_work_level_work_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='hire_success',
            field=models.IntegerField(null=True),
        ),
    ]
