# Generated by Django 4.1.7 on 2023-03-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_project', '0013_member_hire_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hire_success',
            field=models.FloatField(null=True),
        ),
    ]
